# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExcelProcessorUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 271)
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(30)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.uploadBtn = QtWidgets.QPushButton(self.centralwidget)
        self.uploadBtn.setGeometry(QtCore.QRect(40, 30, 338, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.uploadBtn.setFont(font)
        self.uploadBtn.setObjectName("uploadBtn")
        self.downloadBtn = QtWidgets.QPushButton(self.centralwidget)
        self.downloadBtn.setGeometry(QtCore.QRect(40, 120, 338, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.downloadBtn.setFont(font)
        self.downloadBtn.setObjectName("downloadBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Excel 处理器"))
        self.uploadBtn.setText(_translate("MainWindow", "上传Excel文件"))
        self.downloadBtn.setText(_translate("MainWindow", "下载处理后的文件"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
